const router = {
  home: "/",
  product: "/product",
  addProduct: "add-product",
  editProduct: "edit-product/:alias",
  slideshowProduct: "slideshow",
  addSlideshowProduct: "slideshow/add-slideshow",
  editSlideshowProduct: "slideshow/edit-slideshow/:id",
  category: "category",
  user: "/users",
  userTrash: "trash",
  addUser: "add-user",
  editUser: "edit-user/:id",
  blog: "/blog",
  addBlog: "add-blog",
  editBlog: "edit-blog/:alias",
  login: "/login",
  settings: "/settings",
  generalSettings: "general-settings",
  socialsSettings: "socials-settings",
  permission: "permission",
  section: "/section",
  addSection: "add-section",
  editSection: "edit-section/:id",
  me: "/me",
  404: "/404",
  403: "/403"
}

export default router
